### ISSUE TITLE
cramtools-3.0/src/main/java/htsjdk/samtools/cram/lossy/Binning.java:61: error: unmappable character for encoding ASCII

### ISSUE THREAD

**Issue by mmokrejs** [enasequence/cramtools#59]
Hi,
  I am not sure this is a cramtools issue but maybe an issue with htsjdk which you have bundled in your source tree? anyway, looks there are some UTF8 or whatever encoded-chars left in the java file. Java8 is too picky about these, even in comment lines. :(

```
>>> Emerging (1 of 1) sci-biology/cramtools-3.0::science
 * cramtools-3.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                                                                                                            [ ok ]
 * Using: oracle-jdk-bin-1.8
>>> Unpacking source...
>>> Unpacking cramtools-3.0.tar.gz to /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work
>>> Source unpacked in /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work
>>> Preparing source in /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0 ...
>>> Source prepared.
>>> Configuring source in /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0 ...
Rewriting attributes
Rewriting ./build/build.xml
>>> Source configured.
>>> Compiling source in /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0 ...
Buildfile: /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/build/build.xml

clean-dirs:

clean:
   [delete] Deleting: /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/cramtools-3.0.jar

setup:
    [mkdir] Created dir: /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/target/classes

compile:
    [javac] Compiling 82 source files to /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/target/classes
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/htsjdk/samtools/cram/lossy/Binning.java:61: error: unmappable character for encoding ASCII
    [javac]     // ???40 40
    [javac]        ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/htsjdk/samtools/cram/lossy/Binning.java:61: error: unmappable character for encoding ASCII
    [javac]     // ???40 40
    [javac]         ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/htsjdk/samtools/cram/lossy/Binning.java:61: error: unmappable character for encoding ASCII
    [javac]     // ???40 40
    [javac]          ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                 ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                  ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                   ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                    ^
    [javac] /scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/src/main/java/net/sf/cram/common/Utils.java:639: error: unmappable character for encoding ASCII
    [javac]         System.out.println(calculateMD5String("??????".getBytes()));
    [javac]                                                     ^
    [javac] 9 errors

BUILD FAILED
/scratch/var/tmp/portage/sci-biology/cramtools-3.0/work/cramtools-3.0/build/build.xml:147: Compile failed; see the compiler error output for details.

Total time: 3 seconds
 * ERROR: sci-biology/cramtools-3.0::science failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 133:  Called src_compile
 *   environment, line 3965:  Called die
 * The specific snippet of code:
 *       ant -f build/build.xml runnable || die

```

**Comment by jkbonfield** [comment]
I'm having the same issue. Java 1.7.0 and 1.8.0 fail with the unprintable test characters, while 1.6.0 fails for other reasons (too old I assume). 

Is there a recommended release to use, or will it work with 1.8.0 with a different locale?
